# Generated by Django 2.1 on 2018-09-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_count', '0003_auto_20180919_0758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadDetail',
            new_name='ReadDetails',
        ),
    ]
